name: 'Repo: Release'
on:
  repository_dispatch:
    types: [repo_release]

jobs:

  tag:
    runs-on: ubuntu-latest
    name: 'Tag Releases'
    steps:

      - uses: actions/github-script@v2
        env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}

      - uses: actions/github-script@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          script: console.log(context)
